apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-stable
  namespace: canary-demo
  labels:
    app: myapp
    version: stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: stable
  template:
    metadata:
      labels:
        app: myapp
        version: stable
    spec:
      containers:
      - name: app
        image: nginx:1.20
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "v1-stable"
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: app-stable-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-stable-html
  namespace: canary-demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Stable Version</title>
        <style>
            body { font-family: Arial, sans-serif; text-align: center; padding: 50px; background-color: #e8f5e8; }
            h1 { color: #2d5a2d; }
        </style>
    </head>
    <body>
        <h1>Application Version: STABLE (v1)</h1>
        <p>This is the stable version of our application</p>
        <p>Hostname: <span id="hostname"></span></p>
        <script>
            document.getElementById('hostname').textContent = window.location.hostname;
        </script>
    </body>
    </html>
